AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Lambda + DynamoDB + S3 architecture with monthly rotated combined files.

Resources:

  ### S3 Bucket ###
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-uploads"

  ### DynamoDB Table ###
  UploadTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UploadEvents
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: processed
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: processed-index
          KeySchema:
            - AttributeName: processed
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ### Upload Lambda Role ###
  UploadLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-UploadLambdaRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt UploadTable.Arn

  ### Upload Lambda ###
  UploadLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: UploadLambda
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt UploadLambdaRole.Arn
      Timeout: 10
      Code:
        ZipFile: |
          import json
          import boto3
          import uuid
          from datetime import datetime

          dynamodb = boto3.resource("dynamodb")
          table = dynamodb.Table("UploadEvents")

          def lambda_handler(event, context):
              if "body" in event:
                  data = event["body"]
              else:
                  data = json.dumps(event)

              item = {
                  "id": str(uuid.uuid4()),
                  "timestamp": datetime.utcnow().isoformat(),
                  "payload": data,
                  "processed": 0
              }

              table.put_item(Item=item)

              return {
                  "statusCode": 200,
                  "body": json.dumps({"message": "Stored", "id": item["id"]})
              }

  ### Merge Lambda Role ###
  MergeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-MergeLambdaRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                Resource: !GetAtt UploadTable.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "${UploadBucket.Arn}/*"

  ### Merge Lambda with Monthly Rotation ###
  MergeLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MergeLambda
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt MergeLambdaRole.Arn
      Timeout: 60
      Environment:
        Variables:
          BUCKET: !Ref UploadBucket
      Code:
        ZipFile: |
          import boto3
          from boto3.dynamodb.conditions import Key
          import os
          from datetime import datetime

          dynamodb = boto3.resource("dynamodb")
          s3 = boto3.client("s3")

          TABLE_NAME = "UploadEvents"
          table = dynamodb.Table(TABLE_NAME)

          BUCKET = os.environ["BUCKET"]

          def lambda_handler(event, context):
              # Query unprocessed rows
              response = table.query(
                  IndexName="processed-index",
                  KeyConditionExpression=Key("processed").eq(0)
              )

              items = response.get("Items", [])

              if not items:
                  return {"status": "no new data"}

              # Generate filename based on current month
              now = datetime.utcnow()
              filename = f"combined/combined-{now.year}-{now.month:02d}.txt"

              # Download existing monthly combined file
              try:
                  obj = s3.get_object(Bucket=BUCKET, Key=filename)
                  existing_data = obj["Body"].read().decode("utf-8")
              except s3.exceptions.NoSuchKey:
                  existing_data = ""

              # Append new entries
              new_lines = [f"{item['timestamp']} {item['payload']}" for item in items]
              combined_data = existing_data + "\n".join(new_lines) + "\n"

              # Upload updated combined file
              s3.put_object(Bucket=BUCKET, Key=filename, Body=combined_data.encode("utf-8"))

              # Mark items as processed
              for item in items:
                  table.update_item(
                      Key={"id": item["id"], "timestamp": item["timestamp"]},
                      UpdateExpression="SET processed = :p",
                      ExpressionAttributeValues={":p": 1}
                  )

              return {"status": "merged", "entries_added": len(items), "file": filename}

  ### Schedule Merge Lambda (EventBridge Rule) ###
  MergeScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: MergeLambdaSchedule
      # Run at 00:00 UTC on the 1st of every month
      ScheduleExpression: cron(0 0 1 * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt MergeLambda.Arn
          Id: MergeLambdaTarget

  ### Permission for EventBridge to invoke Merge Lambda ###
  MergeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MergeLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MergeScheduleRule.Arn
